INSERT INTO `champs` VALUES ('Aatrox', 'Male', 'Top', 'Darkin', 'Manaless', 'Melee', 'Runeterra,Shurima', 2013);
INSERT INTO `champs` VALUES ('Ahri', 'Female', 'Middle', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2011);
INSERT INTO `champs` VALUES ('Akali', 'Female', 'Top,Middle', 'Human', 'Energy', 'Melee', 'Ionia', 2010);
INSERT INTO `champs` VALUES ('Akshan', 'Male', 'Top,Middle', 'Human', 'Mana', 'Ranged', 'Shurima', 2021);
INSERT INTO `champs` VALUES ('Alistar', 'Male', 'Support', 'Minotaur', 'Mana', 'Melee', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Amumu', 'Male', 'Jungle,Support', 'Yordle,Undead', 'Mana', 'Melee', 'Shurima', 2009);
INSERT INTO `champs` VALUES ('Anivia', 'Female', 'Middle', 'God,Spirit', 'Mana', 'Ranged', 'Freljord', 2009);
INSERT INTO `champs` VALUES ('Annie', 'Female', 'Middle', 'Human,Magically Altered', 'Mana', 'Ranged', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Aphelios', 'Male', 'Bottom', 'Human,Spiritualist', 'Mana', 'Ranged', 'Targon', 2019);
INSERT INTO `champs` VALUES ('Ashe', 'Female', 'Bottom,Support', 'Human,Iceborn', 'Mana', 'Ranged', 'Freljord', 2009);
INSERT INTO `champs` VALUES ('Aurelion Sol', 'Male', 'Middle', 'Celestial,Dragon', 'Mana', 'Ranged', 'Targon,Runeterra', 2016);
INSERT INTO `champs` VALUES ('Azir', 'Male', 'Middle', 'God-Warrior', 'Mana', 'Ranged', 'Shurima', 2014);
INSERT INTO `champs` VALUES ('Bard', 'Male', 'Support', 'Celestial', 'Mana', 'Ranged', 'Runeterra', 2015);
INSERT INTO `champs` VALUES ('Bel\'Veth', 'Female', 'Jungle', 'Void-Being', 'Manaless', 'Melee', 'Void', 2022);
INSERT INTO `champs` VALUES ('Blitzcrank', 'Other', 'Support', 'Golem', 'Mana', 'Melee', 'Zaun', 2009);
INSERT INTO `champs` VALUES ('Brand', 'Male', 'Support', 'Human,Magically Altered', 'Mana', 'Ranged', 'Runeterra', 2011);
INSERT INTO `champs` VALUES ('Braum', 'Male', 'Support', 'Human,Iceborn', 'Mana', 'Melee', 'Freljord', 2014);
INSERT INTO `champs` VALUES ('Caitlyn', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Piltover', 2011);
INSERT INTO `champs` VALUES ('Camille', 'Female', 'Top', 'Human,Cyborg', 'Mana', 'Melee', 'Piltover', 2016);
INSERT INTO `champs` VALUES ('Cassiopeia', 'Female', 'Middle', 'Human,Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010);
INSERT INTO `champs` VALUES ('Cho`Gath', 'Male', 'Top', 'Void-Being', 'Mana', 'Melee', 'Void', 2009);
INSERT INTO `champs` VALUES ('Corki', 'Male', 'Middle', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2009);
INSERT INTO `champs` VALUES ('Darius', 'Male', 'Top', 'Human', 'Mana', 'Melee', 'Noxus', 2012);
INSERT INTO `champs` VALUES ('Diana', 'Female', 'Jungle', 'Aspect,Human', 'Mana', 'Melee', 'Targon', 2012);
INSERT INTO `champs` VALUES ('Dr. Mundo', 'Male', 'Top', 'Human,Chemically Altered', 'Health costs', 'Melee', 'Zaun', 2009);
INSERT INTO `champs` VALUES ('Draven', 'Male', 'Bottom', 'Human', 'Mana', 'Ranged', 'Noxus', 2012);
INSERT INTO `champs` VALUES ('Ekko', 'Male', 'Jungle,Middle', 'Human', 'Mana', 'Melee', 'Zaun', 2015);
INSERT INTO `champs` VALUES ('Elise', 'Female', 'Jungle', 'Human,Magically Altered', 'Mana', 'Both', 'Shadow Isles,Noxus', 2012);
INSERT INTO `champs` VALUES ('Evelynn', 'Female', 'Jungle', 'Spirit,Demon', 'Mana', 'Melee', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Ezreal', 'Male', 'Bottom', 'Human,Magicborn', 'Mana', 'Ranged', 'Piltover', 2010);
INSERT INTO `champs` VALUES ('Fiddlesticks', 'Other', 'Jungle', 'Spirit,Demon', 'Mana', 'Ranged', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Fiora', 'Female', 'Top', 'Human', 'Mana', 'Melee', 'Demacia', 2012);
INSERT INTO `champs` VALUES ('Fizz', 'Male', 'Middle', 'Yordle', 'Mana', 'Melee', 'Bilgewater', 2011);
INSERT INTO `champs` VALUES ('Galio', 'Male', 'Middle,Support', 'Golem', 'Mana', 'Melee', 'Demacia', 2010);
INSERT INTO `champs` VALUES ('Gangplank', 'Male', 'Top,Middle', 'Human', 'Mana', 'Melee', 'Bilgewater', 2009);
INSERT INTO `champs` VALUES ('Garen', 'Male', 'Top', 'Human', 'Manaless', 'Melee', 'Demacia', 2010);
INSERT INTO `champs` VALUES ('Gnar', 'Male', 'Top', 'Yordle', 'Rage', 'Both', 'Freljord', 2014);
INSERT INTO `champs` VALUES ('Gragas', 'Male', 'Top,Jungle', 'Human', 'Mana', 'Melee', 'Freljord', 2010);
INSERT INTO `champs` VALUES ('Graves', 'Male', 'Jungle', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2011);
INSERT INTO `champs` VALUES ('Gwen', 'Female', 'Top', 'Human,Magically Altered', 'Mana', 'Melee', 'Shadow Isles,Camavor', 2021);
INSERT INTO `champs` VALUES ('Hecarim', 'Male', 'Jungle', 'Undead', 'Mana', 'Melee', 'Shadow Isles,Camavor', 2012);
INSERT INTO `champs` VALUES ('Heimerdinger', 'Male', 'Top,Middle', 'Yordle', 'Mana', 'Ranged', 'Piltover', 2009);
INSERT INTO `champs` VALUES ('Illaoi', 'Female', 'Top', 'Human,Spiritualist', 'Mana', 'Melee', 'Bilgewater', 2015);
INSERT INTO `champs` VALUES ('Irelia', 'Female', 'Top,Middle', 'Human,Spiritualist', 'Mana', 'Melee', 'Ionia', 2010);
INSERT INTO `champs` VALUES ('Ivern', 'Male', 'Jungle', 'Human,Magically Altered', 'Mana', 'Ranged', 'Ionia,Freljord', 2016);
INSERT INTO `champs` VALUES ('Janna', 'Female', 'Support', 'God,Spirit', 'Mana', 'Ranged', 'Shurima,Zaun', 2009);
INSERT INTO `champs` VALUES ('Jarvan IV', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Demacia', 2011);
INSERT INTO `champs` VALUES ('Jax', 'Male', 'Top', 'Unknown', 'Mana', 'Melee', 'Icathia,Runeterra,Shurima', 2009);
INSERT INTO `champs` VALUES ('Jayce', 'Male', 'Top,Middle', 'Human', 'Mana', 'Both', 'Piltover', 2012);
INSERT INTO `champs` VALUES ('Jhin', 'Male', 'Bottom', 'Human,Spiritualist', 'Mana', 'Ranged', 'Ionia', 2016);
INSERT INTO `champs` VALUES ('Jinx', 'Female', 'Bottom', 'Human,Chemically Altered', 'Mana', 'Ranged', 'Zaun', 2013);
INSERT INTO `champs` VALUES ('Kai\'Sa', 'Female', 'Bottom', 'Human,Void-Being', 'Mana', 'Ranged', 'Shurima,Void', 2018);
INSERT INTO `champs` VALUES ('Kalista', 'Female', 'Bottom', 'Undead', 'Mana', 'Ranged', 'Shadow Isles,Camavor', 2014);
INSERT INTO `champs` VALUES ('Karma', 'Female', 'Support', 'Human,Spiritualist', 'Mana', 'Ranged', 'Ionia', 2011);
INSERT INTO `champs` VALUES ('Karthus', 'Male', 'Jungle', 'Undead', 'Mana', 'Ranged', 'Shadow Isles,Noxus', 2009);
INSERT INTO `champs` VALUES ('Kassadin', 'Male', 'Middle', 'Human,Void-Being', 'Mana', 'Melee', 'Shurima,Void', 2009);
INSERT INTO `champs` VALUES ('Katarina', 'Female', 'Middle', 'Human', 'Manaless', 'Melee', 'Noxus', 2009);
INSERT INTO `champs` VALUES ('Kayle', 'Female', 'Top', 'Aspect,Human,Magically Altered', 'Mana', 'Both', 'Targon,Demacia', 2009);
INSERT INTO `champs` VALUES ('Kayn', 'Male', 'Jungle', 'Human,Magically Altered,Darkin', 'Mana', 'Melee', 'Runeterra,Shurima,Ionia,Noxus', 2017);
INSERT INTO `champs` VALUES ('Kennen', 'Male', 'Top', 'Yordle', 'Energy', 'Ranged', 'Ionia', 2010);
INSERT INTO `champs` VALUES ('Kha\'Zix', 'Male', 'Jungle', 'Void-Being', 'Mana', 'Melee', 'Void', 2012);
INSERT INTO `champs` VALUES ('Kindred', 'Other', 'Jungle', 'God,Spirit', 'Mana', 'Ranged', 'Runeterra', 2015);
INSERT INTO `champs` VALUES ('Kled', 'Male', 'Top', 'Yordle', 'Courage', 'Melee', 'Noxus', 2016);
INSERT INTO `champs` VALUES ('Kog\'Maw', 'Male', 'Bottom', 'Void-Being', 'Mana', 'Ranged', 'Void', 2010);
INSERT INTO `champs` VALUES ('LeBlanc', 'Female', 'Middle', 'Human,Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010);
INSERT INTO `champs` VALUES ('Lee Sin', 'Male', 'Jungle', 'Human,Spiritualist', 'Energy', 'Melee', 'Ionia', 2011);
INSERT INTO `champs` VALUES ('Leona', 'Female', 'Support', 'Aspect,Human', 'Mana', 'Melee', 'Targon', 2011);
INSERT INTO `champs` VALUES ('Lillia', 'Female', 'Top,Jungle', 'Spirit', 'Mana', 'Ranged', 'Ionia', 2020);
INSERT INTO `champs` VALUES ('Lissandra', 'Female', 'Middle', 'Human,Iceborn', 'Mana', 'Ranged', 'Freljord', 2013);
INSERT INTO `champs` VALUES ('Lucian', 'Male', 'Bottom', 'Human', 'Mana', 'Ranged', 'Blessed Isles,Demacia', 2013);
INSERT INTO `champs` VALUES ('Lulu', 'Female', 'Support', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2012);
INSERT INTO `champs` VALUES ('Lux', 'Female', 'Middle,Support', 'Human,Magicborn', 'Mana', 'Ranged', 'Demacia', 2010);
INSERT INTO `champs` VALUES ('Malphite', 'Male', 'Top', 'Golem', 'Mana', 'Melee', 'Ixtal,Shurima', 2009);
INSERT INTO `champs` VALUES ('Malzahar', 'Male', 'Middle', 'Human,Void-Being', 'Mana', 'Ranged', 'Shurima,Void', 2010);
INSERT INTO `champs` VALUES ('Maokai', 'Male', 'Top,Support', 'Spirit', 'Mana', 'Melee', 'Blessed Isles,Shadow Isles', 2011);
INSERT INTO `champs` VALUES ('Master Yi', 'Male', 'Jungle', 'Human,Spiritualist', 'Mana', 'Melee', 'Ionia', 2009);
INSERT INTO `champs` VALUES ('Miss Fortune', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Bilgewater', 2010);
INSERT INTO `champs` VALUES ('Mordekaiser', 'Male', 'Top', 'Revenant', 'Shield', 'Melee', 'Noxus', 2010);
INSERT INTO `champs` VALUES ('Morgana', 'Female', 'Support', 'Aspect,Human,Magically Altered', 'Mana', 'Ranged', 'Targon,Demacia', 2009);
INSERT INTO `champs` VALUES ('Nami', 'Female', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Runeterra', 2012);
INSERT INTO `champs` VALUES ('Nasus', 'Male', 'Top', 'God-Warrior', 'Mana', 'Melee', 'Shurima', 2009);
INSERT INTO `champs` VALUES ('Nautilus', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2012);
INSERT INTO `champs` VALUES ('Neeko', 'Female', 'Middle,Support', 'Vastayan', 'Mana', 'Ranged', 'Ixtal', 2018);
INSERT INTO `champs` VALUES ('Nidalee', 'Female', 'Jungle', 'Human,Vastayan,Spiritualist', 'Mana', 'Both', 'Ixtal', 2009);
INSERT INTO `champs` VALUES ('Nilah', 'Female', 'Bottom', 'Human,Magically Altered', 'Mana', 'Melee', 'Bilgewater', 2022);
INSERT INTO `champs` VALUES ('Nocturne', 'Male', 'Jungle', 'Spirit,Demon', 'Mana', 'Melee', 'Runeterra', 2011);
INSERT INTO `champs` VALUES ('Nunu & Willump', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Freljord', 2009);
INSERT INTO `champs` VALUES ('Olaf', 'Male', 'Top,Jungle', 'Human,Iceborn', 'Mana', 'Melee', 'Freljord', 2010);
INSERT INTO `champs` VALUES ('Orianna', 'Female', 'Middle', 'Golem', 'Mana', 'Ranged', 'Piltover', 2011);
INSERT INTO `champs` VALUES ('Ornn', 'Male', 'Top', 'God,Spirit', 'Mana', 'Melee', 'Freljord', 2017);
INSERT INTO `champs` VALUES ('Pantheon', 'Male', 'Jungle,Middle,Support', 'Aspect,Human', 'Mana', 'Melee', 'Targon', 2010);
INSERT INTO `champs` VALUES ('Poppy', 'Female', 'Top,Jungle', 'Yordle', 'Mana', 'Melee', 'Demacia', 2010);
INSERT INTO `champs` VALUES ('Pyke', 'Male', 'Support', 'Revenant', 'Mana', 'Melee', 'Bilgewater', 2018);
INSERT INTO `champs` VALUES ('Qiyana', 'Female', 'Jungle,Middle', 'Human,Magicborn', 'Mana', 'Melee', 'Ixtal', 2019);
INSERT INTO `champs` VALUES ('Quinn', 'Female', 'Top', 'Human', 'Mana', 'Ranged', 'Demacia', 2013);
INSERT INTO `champs` VALUES ('Rakan', 'Male', 'Support', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2017);
INSERT INTO `champs` VALUES ('Rammus', 'Male', 'Jungle', 'God-Warrior', 'Mana', 'Melee', 'Shurima', 2009);
INSERT INTO `champs` VALUES ('Rek\'Sai', 'Female', 'Jungle', 'Void-Being', 'Rage', 'Melee', 'Void', 2014);
INSERT INTO `champs` VALUES ('Rell', 'Female', 'Support', 'Human,Magicborn,Magically Altered', 'Mana', 'Melee', 'Noxus', 2020);
INSERT INTO `champs` VALUES ('Renata Glasc', 'Female', 'Support', 'Human,Chemically Altered', 'Mana', 'Ranged', 'Zaun', 2022);
INSERT INTO `champs` VALUES ('Renekton', 'Male', 'Top', 'God-Warrior', 'Fury', 'Melee', 'Shurima', 2011);
INSERT INTO `champs` VALUES ('Rengar', 'Male', 'Top,Jungle', 'Vastayan', 'Ferocity', 'Melee', 'Ixtal', 2012);
INSERT INTO `champs` VALUES ('Riven', 'Female', 'Top', 'Human', 'Manaless', 'Melee', 'Ionia,Noxus', 2011);
INSERT INTO `champs` VALUES ('Rumble', 'Male', 'Top,Middle', 'Yordle', 'Heat', 'Melee', 'Bandle City', 2011);
INSERT INTO `champs` VALUES ('Ryze', 'Male', 'Top,Middle', 'Human,Magically Altered', 'Mana', 'Ranged', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Samira', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Shurima,Noxus', 2020);
INSERT INTO `champs` VALUES ('Sejuani', 'Female', 'Top,Jungle', 'Human,Iceborn', 'Mana', 'Melee', 'Freljord', 2012);
INSERT INTO `champs` VALUES ('Senna', 'Female', 'Support', 'Human,Undead', 'Mana', 'Ranged', 'Blessed Isles', 2019);
INSERT INTO `champs` VALUES ('Seraphine', 'Female', 'Support', 'Human,Magicborn', 'Mana', 'Ranged', 'Piltover,Zaun', 2020);
INSERT INTO `champs` VALUES ('Sett', 'Male', 'Top', 'Human,Vastayan', 'Grit', 'Melee', 'Ionia', 2020);
INSERT INTO `champs` VALUES ('Shaco', 'Male', 'Jungle', 'Spirit', 'Mana', 'Melee', 'Runeterra', 2009);
INSERT INTO `champs` VALUES ('Shen', 'Male', 'Top', 'Human,Spiritualist', 'Energy', 'Melee', 'Ionia', 2010);
INSERT INTO `champs` VALUES ('Shyvana', 'Female', 'Jungle', 'Magically Altered,Dragon', 'Fury', 'Melee', 'Demacia', 2011);
INSERT INTO `champs` VALUES ('Singed', 'Male', 'Top', 'Human,Chemically Altered', 'Mana', 'Melee', 'Piltover,Zaun', 2009);
INSERT INTO `champs` VALUES ('Sion', 'Male', 'Top', 'Revenant', 'Mana', 'Melee', 'Noxus', 2009);
INSERT INTO `champs` VALUES ('Sivir', 'Female', 'Bottom', 'Human', 'Mana', 'Ranged', 'Shurima', 2009);
INSERT INTO `champs` VALUES ('Skarner', 'Male', 'Jungle', 'Brackern', 'Mana', 'Melee', 'Shurima', 2011);
INSERT INTO `champs` VALUES ('Sona', 'Female', 'Support', 'Human,Magicborn', 'Mana', 'Ranged', 'Demacia', 2010);
INSERT INTO `champs` VALUES ('Soraka', 'Female', 'Support', 'Celestial', 'Mana', 'Ranged', 'Targon,Ionia', 2009);
INSERT INTO `champs` VALUES ('Swain', 'Male', 'Middle,Support', 'Human,Magically Altered', 'Mana', 'Ranged', 'Noxus', 2010);
INSERT INTO `champs` VALUES ('Sylas', 'Male', 'Middle', 'Human,Magicborn', 'Mana', 'Melee', 'Demacia,Freljord', 2019);
INSERT INTO `champs` VALUES ('Syndra', 'Female', 'Middle', 'Human,Magicborn', 'Mana', 'Ranged', 'Ionia', 2012);
INSERT INTO `champs` VALUES ('Tahm Kench', 'Male', 'Top,Support', 'Spirit,Demon', 'Mana', 'Melee', 'Runeterra,Bilgewater', 2015);
INSERT INTO `champs` VALUES ('Taliyah', 'Female', 'Jungle,Middle', 'Human,Magicborn', 'Mana', 'Ranged', 'Shurima', 2016);
INSERT INTO `champs` VALUES ('Talon', 'Male', 'Jungle,Middle', 'Human', 'Mana', 'Melee', 'Noxus', 2011);
INSERT INTO `champs` VALUES ('Taric', 'Male', 'Support', 'Aspect,Human', 'Mana', 'Melee', 'Targon,Demacia', 2009);
INSERT INTO `champs` VALUES ('Teemo', 'Male', 'Top', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2009);
INSERT INTO `champs` VALUES ('Thresh', 'Male', 'Support', 'Undead', 'Mana', 'Ranged', 'Blessed Isles,Shadow Isles', 2013);
INSERT INTO `champs` VALUES ('Tristana', 'Female', 'Bottom', 'Yordle', 'Mana', 'Ranged', 'Bandle City', 2009);
INSERT INTO `champs` VALUES ('Trundle', 'Male', 'Top,Jungle', 'Iceborn,Troll', 'Mana', 'Melee', 'Freljord', 2010);
INSERT INTO `champs` VALUES ('Tryndamere', 'Male', 'Top', 'Human,Magically Altered', 'Fury', 'Melee', 'Freljord', 2009);
INSERT INTO `champs` VALUES ('Twisted Fate', 'Male', 'Middle', 'Human,Magicborn', 'Mana', 'Ranged', 'Bilgewater', 2009);
INSERT INTO `champs` VALUES ('Twitch', 'Male', 'Bottom', 'Chemically Altered,Rat', 'Mana', 'Ranged', 'Zaun', 2009);
INSERT INTO `champs` VALUES ('Udyr', 'Male', 'Top,Jungle', 'Human,Vastayan,Spiritualist', 'Mana', 'Melee', 'Ionia,Freljord', 2009);
INSERT INTO `champs` VALUES ('Urgot', 'Male', 'Top', 'Human,Chemically Altered,Cyborg', 'Mana', 'Ranged', 'Zaun,Noxus', 2010);
INSERT INTO `champs` VALUES ('Varus', 'Male', 'Middle,Bottom', 'Human,Darkin', 'Mana', 'Ranged', 'Runeterra,Shurima,Ionia', 2012);
INSERT INTO `champs` VALUES ('Vayne', 'Female', 'Top,Bottom', 'Human', 'Mana', 'Ranged', 'Demacia', 2011);
INSERT INTO `champs` VALUES ('Veigar', 'Male', 'Middle', 'Yordle', 'Mana', 'Ranged', 'Runeterra,Bandle City', 2009);
INSERT INTO `champs` VALUES ('Vel\'Koz', 'Male', 'Middle,Support', 'Void-Being', 'Mana', 'Ranged', 'Void', 2014);
INSERT INTO `champs` VALUES ('Vex', 'Female', 'Middle', 'Yordle', 'Mana', 'Ranged', 'Bandle City,Shadow Isles', 2021);
INSERT INTO `champs` VALUES ('Vi', 'Female', 'Jungle', 'Human', 'Mana', 'Melee', 'Piltover,Zaun', 2012);
INSERT INTO `champs` VALUES ('Viego', 'Male', 'Jungle', 'Undead', 'Manaless', 'Melee', 'Shadow Isles,Camavor', 2021);
INSERT INTO `champs` VALUES ('Viktor', 'Male', 'Middle', 'Human,Cyborg', 'Mana', 'Ranged', 'Zaun', 2011);
INSERT INTO `champs` VALUES ('Vladimir', 'Male', 'Middle', 'Human,Magically Altered', 'Bloodthirst', 'Ranged', 'Blessed Isles,Noxus,Camavor', 2010);
INSERT INTO `champs` VALUES ('Volibear', 'Male', 'Top,Jungle', 'God,Spirit', 'Mana', 'Melee', 'Freljord', 2011);
INSERT INTO `champs` VALUES ('Warwick', 'Male', 'Top,Jungle', 'Human,Chemically Altered,Cyborg', 'Mana', 'Melee', 'Zaun', 2009);
INSERT INTO `champs` VALUES ('Wukong', 'Male', 'Top,Jungle', 'Vastayan', 'Mana', 'Melee', 'Ionia', 2011);
INSERT INTO `champs` VALUES ('Xayah', 'Female', 'Bottom', 'Vastayan', 'Mana', 'Ranged', 'Ionia', 2017);
INSERT INTO `champs` VALUES ('Xerath', 'Male', 'Middle,Support', 'God-Warrior', 'Mana', 'Ranged', 'Shurima', 2011);
INSERT INTO `champs` VALUES ('Xin Zhao', 'Male', 'Jungle', 'Human', 'Mana', 'Melee', 'Ionia,Demacia,Noxus', 2010);
INSERT INTO `champs` VALUES ('Yasuo', 'Male', 'Middle', 'Human,Magicborn', 'Flow', 'Melee', 'Ionia', 2013);
INSERT INTO `champs` VALUES ('Yone', 'Male', 'Top,Middle', 'Human,Magically Altered', 'Manaless', 'Melee', 'Ionia', 2020);
INSERT INTO `champs` VALUES ('Yorick', 'Male', 'Top', 'Human,Magically Altered', 'Mana', 'Melee', 'Blessed Isles,Shadow Isles', 2011);
INSERT INTO `champs` VALUES ('Yuumi', 'Female', 'Support', 'Magically Altered,Cat', 'Mana', 'Ranged', 'Bandle City', 2019);
INSERT INTO `champs` VALUES ('Zac', 'Male', 'Jungle', 'Golem', 'Health costs', 'Melee', 'Zaun', 2013);
INSERT INTO `champs` VALUES ('Zed', 'Male', 'Middle', 'Human,Magically Altered', 'Energy', 'Melee', 'Ionia', 2012);
INSERT INTO `champs` VALUES ('Zeri', 'Female', 'Bottom', 'Human,Magicborn', 'Mana', 'Ranged', 'Zaun', 2022);
INSERT INTO `champs` VALUES ('Ziggs', 'Male', 'Middle,Bottom', 'Yordle', 'Mana', 'Ranged', 'Piltover,Zaun', 2012);
INSERT INTO `champs` VALUES ('Zilean', 'Male', 'Support', 'Human,Magicborn', 'Mana', 'Ranged', 'Icathia,Runeterra,Shurima', 2009);
INSERT INTO `champs` VALUES ('Zoe', 'Female', 'Middle', 'Aspect,Human', 'Mana', 'Ranged', 'Targon', 2017);
INSERT INTO `champs` VALUES ('Zyra', 'Female', 'Support', 'Unknown', 'Mana', 'Ranged', 'Ixtal', 2012);
